# Generated by Django 5.0.6 on 2024-11-23 03:53

import models_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelentry',
            name='model_file',
            field=models.FileField(upload_to='models/', validators=[models_app.models.validate_onnx_model]),
        ),
    ]
